// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_queries.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExternalIdentity = `-- name: CreateExternalIdentity :one
INSERT INTO auth.external_identities (
    user_id,
    provider,
    provider_subject,
    provider_username
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    user_id,
    provider,
    provider_subject,
    provider_username,
    created_at,
    updated_at
`

type CreateExternalIdentityParams struct {
	UserID           pgtype.UUID
	Provider         string
	ProviderSubject  string
	ProviderUsername pgtype.Text
}

func (q *Queries) CreateExternalIdentity(ctx context.Context, arg CreateExternalIdentityParams) (AuthExternalIdentity, error) {
	row := q.db.QueryRow(ctx, createExternalIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.ProviderUsername,
	)
	var i AuthExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.ProviderUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO auth.refresh_sessions (
    user_id,
    token_hash,
    user_agent,
    ip,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    user_id,
    token_hash,
    user_agent,
    ip,
    expires_at,
    revoked_at,
    created_at
`

type CreateRefreshSessionParams struct {
	UserID    pgtype.UUID
	TokenHash string
	UserAgent pgtype.Text
	Ip        *netip.Addr
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (AuthRefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i AuthRefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (
    username,
    email,
    tg_username,
    name,
    surname
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    username,
    email,
    tg_username,
    name,
    surname,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Username   string
	Email      string
	TgUsername pgtype.Text
	Name       pgtype.Text
	Surname    pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.TgUsername,
		arg.Name,
		arg.Surname,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.TgUsername,
		&i.Name,
		&i.Surname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserPassword = `-- name: CreateUserPassword :one
INSERT INTO auth.user_passwords (
    user_id,
    password_hash
) VALUES (
    $1,
    $2
)
RETURNING
    id,
    user_id,
    password_hash
`

type CreateUserPasswordParams struct {
	UserID       pgtype.UUID
	PasswordHash string
}

func (q *Queries) CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) (AuthUserPassword, error) {
	row := q.db.QueryRow(ctx, createUserPassword, arg.UserID, arg.PasswordHash)
	var i AuthUserPassword
	err := row.Scan(&i.ID, &i.UserID, &i.PasswordHash)
	return i, err
}

const findUserConflicts = `-- name: FindUserConflicts :many
SELECT field
FROM (
  SELECT 1 AS priority, 'username' AS field
  WHERE EXISTS (SELECT 1 FROM auth.users AS u WHERE u.username = $1)
  UNION ALL
  SELECT 2 AS priority, 'email' AS field
  WHERE EXISTS (SELECT 1 FROM auth.users AS u WHERE LOWER(u.email) = LOWER($2::text))
  UNION ALL
  SELECT 3 AS priority, 'tg_username' AS field
  WHERE $3::text IS NOT NULL
    AND EXISTS (SELECT 1 FROM auth.users AS u WHERE u.tg_username = $3)
) AS conflicts
ORDER BY priority
`

type FindUserConflictsParams struct {
	Username   string
	Email      string
	TgUsername pgtype.Text
}

func (q *Queries) FindUserConflicts(ctx context.Context, arg FindUserConflictsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, findUserConflicts, arg.Username, arg.Email, arg.TgUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var field string
		if err := rows.Scan(&field); err != nil {
			return nil, err
		}
		items = append(items, field)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByExternalIdentity = `-- name: GetUserByExternalIdentity :one
SELECT
    u.id,
    u.username,
    u.email,
    u.tg_username,
    u.name,
    u.surname,
    u.created_at,
    u.updated_at
FROM auth.external_identities AS ei
JOIN auth.users AS u ON u.id = ei.user_id
WHERE ei.provider = $1
  AND ei.provider_subject = $2
LIMIT 1
`

type GetUserByExternalIdentityParams struct {
	Provider        string
	ProviderSubject string
}

func (q *Queries) GetUserByExternalIdentity(ctx context.Context, arg GetUserByExternalIdentityParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByExternalIdentity, arg.Provider, arg.ProviderSubject)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.TgUsername,
		&i.Name,
		&i.Surname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredentialsByLogin = `-- name: GetUserCredentialsByLogin :one
SELECT
    u.id,
    u.username,
    u.email,
    u.tg_username,
    u.name,
    u.surname,
    u.created_at,
    u.updated_at,
    up.password_hash
FROM auth.users AS u
JOIN auth.user_passwords AS up ON up.user_id = u.id
WHERE u.username = $1
   OR LOWER(u.email) = LOWER($1::text)
LIMIT 1
`

type GetUserCredentialsByLoginRow struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	TgUsername   pgtype.Text
	Name         pgtype.Text
	Surname      pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	PasswordHash string
}

func (q *Queries) GetUserCredentialsByLogin(ctx context.Context, username string) (GetUserCredentialsByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByLogin, username)
	var i GetUserCredentialsByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.TgUsername,
		&i.Name,
		&i.Surname,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :one
UPDATE auth.refresh_sessions
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
RETURNING
    user_id,
    user_agent
`

type RevokeRefreshSessionRow struct {
	UserID    pgtype.UUID
	UserAgent pgtype.Text
}

func (q *Queries) RevokeRefreshSession(ctx context.Context, tokenHash string) (RevokeRefreshSessionRow, error) {
	row := q.db.QueryRow(ctx, revokeRefreshSession, tokenHash)
	var i RevokeRefreshSessionRow
	err := row.Scan(&i.UserID, &i.UserAgent)
	return i, err
}
