// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthExternalIdentity struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Provider         string
	ProviderSubject  string
	ProviderUsername pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AuthRefreshSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	UserAgent pgtype.Text
	Ip        *netip.Addr
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AuthUser struct {
	ID         pgtype.UUID
	Username   string
	Email      string
	TgUsername pgtype.Text
	Name       pgtype.Text
	Surname    pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type AuthUserPassword struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	PasswordHash string
}
